name: "C++ Linter: clang-tidy"

on:
  pull_request:
    branches: [ main ]
  push:
    tags:
      - '[0-9]+.*'
jobs:
  Cpp-linter:
    runs-on: ubuntu-latest

    permissions:
      contents: read 
      pull-requests: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          sudo sh -c "wget -O - https://dl.openfoam.org/gpg.key | apt-key add -"
          sudo add-apt-repository http://dl.openfoam.org/ubuntu
          sudo apt-get update
          sudo apt-get -y install openfoam13 wget
          sudo apt-get install -y libc6 wget lsb-release software-properties-common gnupg bear


      - name: Compile Solver and Utilities
        run: |
          bash -ic '
            set +m
            
            # Il .bashrc è stato modificato da "conda init"
            # Quindi l''attivazione funzionerà
            conda activate OpenPDACconda
            
            # Ora carica OpenFOAM
            source /opt/openfoam13/etc/bashrc
            
            # Compila
            echo "Compiling OpenPDAC solver..."
            cd applications/OpenPDAC
            bear -- ./Allwmake
          '

      - name: Run cpp-linter with clang-tidy
        uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Path to the compilation database generated by Bear
          database: 'applications/OpenPDAC/'
          style: ''
          tidy-checks: ''

      - name: Fail fast?!
        if: steps.linter.outputs.checks-failed > 0
        run: exit 1
